// <auto-generated />
using System;
using BurgerHUB.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BurgerHUB.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BurgerHUB.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdClient")
                        .HasColumnType("integer");

                    b.Property<int>("IdDeliveryMan")
                        .HasColumnType("integer");

                    b.Property<int>("IdPayment")
                        .HasColumnType("integer");

                    b.Property<int>("IdPosition")
                        .HasColumnType("integer");

                    b.Property<int>("IsActive")
                        .HasColumnType("integer");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("IdClient")
                        .IsUnique();

                    b.HasIndex("IdDeliveryMan")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Validity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdOrder")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountBC")
                        .HasColumnType("integer");

                    b.Property<int>("AmountBM")
                        .HasColumnType("integer");

                    b.Property<int>("BC")
                        .HasColumnType("integer");

                    b.Property<int>("BM")
                        .HasColumnType("integer");

                    b.Property<int>("IdBurgerCons")
                        .HasColumnType("integer");

                    b.Property<int>("IdBurgerMenu")
                        .HasColumnType("integer");

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdBurgerCons")
                        .IsUnique();

                    b.HasIndex("IdBurgerMenu")
                        .IsUnique();

                    b.HasIndex("IdOrder")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Supplement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBurgerCons")
                        .HasColumnType("integer");

                    b.Property<int>("IdBurgerMenu")
                        .HasColumnType("integer");

                    b.Property<int>("IdIngridient")
                        .HasColumnType("integer");

                    b.Property<int>("calories")
                        .HasColumnType("integer");

                    b.Property<int>("carbohydrates")
                        .HasColumnType("integer");

                    b.Property<int>("fasts")
                        .HasColumnType("integer");

                    b.Property<int>("proteins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdBurgerCons")
                        .IsUnique();

                    b.HasIndex("IdBurgerMenu")
                        .IsUnique();

                    b.HasIndex("IdIngridient")
                        .IsUnique();

                    b.ToTable("Supplements");
                });

            modelBuilder.Entity("BurgerHUB.Models.BurgerCons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("IDSupplement")
                        .HasColumnType("integer");

                    b.Property<int>("IdPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Weight_gram")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BurgerCons");
                });

            modelBuilder.Entity("BurgerHUB.Models.BurgerMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CookTime_min")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IDSupplement")
                        .HasColumnType("integer");

                    b.Property<string>("IMG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdPosition")
                        .HasColumnType("integer");

                    b.Property<int>("IsEco")
                        .HasColumnType("integer");

                    b.Property<int>("IsHit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Weight_gram")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("burgerMenus");
                });

            modelBuilder.Entity("BurgerHUB.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Raiting")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BurgerHUB.Models.DeliveryMan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("IdOrder")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("deliveryMen");
                });

            modelBuilder.Entity("BurgerHUB.Models.Ingridient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BurgerConsId")
                        .HasColumnType("integer");

                    b.Property<string>("IMG_side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IMG_top")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdSupplement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Weight_gram")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BurgerConsId");

                    b.ToTable("Ingridients");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Order", b =>
                {
                    b.HasOne("BurgerHUB.Models.Client", "Client")
                        .WithMany("OrderHistory")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Models.Client", null)
                        .WithOne("Order")
                        .HasForeignKey("BurgerHUB.Data.Models.Order", "IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Models.DeliveryMan", "DeliveryMan")
                        .WithOne("Order")
                        .HasForeignKey("BurgerHUB.Data.Models.Order", "IdDeliveryMan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DeliveryMan");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Payment", b =>
                {
                    b.HasOne("BurgerHUB.Data.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("BurgerHUB.Data.Models.Payment", "IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Position", b =>
                {
                    b.HasOne("BurgerHUB.Models.BurgerCons", "BurgerCons")
                        .WithOne("Position")
                        .HasForeignKey("BurgerHUB.Data.Models.Position", "IdBurgerCons")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Models.BurgerMenu", "BurgerMenu")
                        .WithOne("Position")
                        .HasForeignKey("BurgerHUB.Data.Models.Position", "IdBurgerMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Data.Models.Order", "Order")
                        .WithOne("Position")
                        .HasForeignKey("BurgerHUB.Data.Models.Position", "IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Data.Models.Order", null)
                        .WithMany("Positions")
                        .HasForeignKey("OrderId");

                    b.Navigation("BurgerCons");

                    b.Navigation("BurgerMenu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Supplement", b =>
                {
                    b.HasOne("BurgerHUB.Models.BurgerCons", "BurgerCons")
                        .WithOne("Supplement")
                        .HasForeignKey("BurgerHUB.Data.Models.Supplement", "IdBurgerCons")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Models.BurgerMenu", "BurgerMenu")
                        .WithOne("Supplement")
                        .HasForeignKey("BurgerHUB.Data.Models.Supplement", "IdBurgerMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerHUB.Models.Ingridient", "Ingridient")
                        .WithOne("Supplement")
                        .HasForeignKey("BurgerHUB.Data.Models.Supplement", "IdIngridient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BurgerCons");

                    b.Navigation("BurgerMenu");

                    b.Navigation("Ingridient");
                });

            modelBuilder.Entity("BurgerHUB.Models.BurgerCons", b =>
                {
                    b.HasOne("BurgerHUB.Models.Client", null)
                        .WithMany("MyBurgers")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("BurgerHUB.Models.Ingridient", b =>
                {
                    b.HasOne("BurgerHUB.Models.BurgerCons", "BurgerCons")
                        .WithMany("Ingridients")
                        .HasForeignKey("BurgerConsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BurgerCons");
                });

            modelBuilder.Entity("BurgerHUB.Data.Models.Order", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("BurgerHUB.Models.BurgerCons", b =>
                {
                    b.Navigation("Ingridients");

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Supplement")
                        .IsRequired();
                });

            modelBuilder.Entity("BurgerHUB.Models.BurgerMenu", b =>
                {
                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Supplement")
                        .IsRequired();
                });

            modelBuilder.Entity("BurgerHUB.Models.Client", b =>
                {
                    b.Navigation("MyBurgers");

                    b.Navigation("Order")
                        .IsRequired();

                    b.Navigation("OrderHistory");
                });

            modelBuilder.Entity("BurgerHUB.Models.DeliveryMan", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });

            modelBuilder.Entity("BurgerHUB.Models.Ingridient", b =>
                {
                    b.Navigation("Supplement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
